---
# Development related tasks

# Apache
- name: Apache
  apt: pkg=apache2 state=installed

- name: Apache Modules
  command: a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter

# PHP
- name: PHP 5.5 Custom Repo
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- name: PHP and Modules
  apt: pkg={{ item }} state=latest
  notify: restart apache
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-gd
    - php-apc
    - php5-mcrypt
    - php5-curl
    - php5-intl
    - php5-memcached
    - php5-xdebug
    - sqlite3

# Configurations

- name: PHP | Copying XDebug Config
  copy: src=../files/xdebug.ini dest=/etc/php5/mods-available/xdebug.ini
  notify:
    - restart apache

- name: PHP | Config timezone
  ini_file: dest=/etc/php5/mods-available/timezone.ini section=Date option=date.timezone value={{ timezone }}
  notify:
    - restart apache

- name: PHP | Enable Custom Config
  shell: php5enmod -s ALL timezone

- name: PHP | Enable XDebug Config
  shell: php5enmod -s ALL xdebug

# PHP Tools

- name: Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
