---
- name: Apache | Copy Host Config
  template: src=../files/laravel.conf dest=/etc/apache2/sites-available/laravel.conf

- name: Apache | Enable Host Config
  command: a2ensite laravel.conf
  notify: restart apache

- name: Apache | Disable Default Host Config
  command: a2dissite 000-default.conf
  notify: restart apache

- name: Apache | Ensure application files are present
  file: path={{ document_root }} state=directory
