---
- hosts: "all"
  sudo: yes
  vars:
    root_folder: /var/www/sites/www.sunshinecoastgolf.org/golf
    document_root: "{{ root_folder }}/public"
    timezone: Australia/Brisbane
    writeable_dirs:
      - app/storage/cache
  tasks:
    - include: tasks/common.yml
    - include: tasks/development.yml
    - include: tasks/host.yml
    - include: tasks/app.yml

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

